version: '3.9'

services:
  app:
    image: spotify-streamlit
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run src/app.py
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"
